# SPDX-License-Identifier: GPL-2.0

OPPEN_MODULES = [
    # keep sorted
    "arch/arm64/crypto/sha1-ce.ko",
    "drivers/clk/clk-scmi.ko",
    "drivers/i2c/i2c-dev.ko",
    "drivers/leds/leds-gpio.ko",
    "drivers/media/v4l2-core/v4l2-async.ko",
    "drivers/media/v4l2-core/v4l2-fwnode.ko",
    "drivers/net/mdio/mdio-mux.ko",
    "drivers/net/pcs/pcs_xpcs.ko",
    "drivers/regulator/gpio-regulator.ko",
    "drivers/rtc/rtc-hym8563.ko",
    "fs/ntfs3/ntfs3.ko",
    "net/mac80211/mac80211.ko",
    "net/wireless/cfg80211.ko",
]

COMMON_DRIVERS_MODULES = [
    # keep sorted
    "common_drivers/drivers/char/aml-gpiomem.ko",
    "common_drivers/drivers/clk/meson/amlogic-clk-soc-s6.ko",
    "common_drivers/drivers/clk/meson/amlogic-clk-soc-s7.ko",
    "common_drivers/drivers/clk/meson/amlogic-clk-soc-s7d.ko",
    "common_drivers/drivers/crypto/amlogic-crypto-dma.ko",
    "common_drivers/drivers/debug/amlogic-audio-utils.ko",
    "common_drivers/drivers/drm/aml_drm.ko",
    "common_drivers/drivers/dvb/demux/amlogic-dvb-demux.ko",
    "common_drivers/drivers/dvb/dummy_fe/amlogic-dummy-fe.ko",
    "common_drivers/drivers/dvb_ci/amlogic-dvb-ci.ko",
    "common_drivers/drivers/dvb_usbci/amlogic-usb-cam.ko",
    "common_drivers/drivers/gpio/amlogic-pinctrl-soc-s6.ko",
    "common_drivers/drivers/gpio/amlogic-pinctrl-soc-s7.ko",
    "common_drivers/drivers/gpio/amlogic-pinctrl-soc-s7d.ko",
    "common_drivers/drivers/host/amlogic-host.ko",
    "common_drivers/drivers/hwspinlock/amlogic-hwspinlock.ko",
    "common_drivers/drivers/iio/adc/amlogic-adc.ko",
    "common_drivers/drivers/irblaster/amlogic-irblaster.ko",
    "common_drivers/drivers/jtag/amlogic-jtag.ko",
    "common_drivers/drivers/led/amlogic-led.ko",
    "common_drivers/drivers/media/camera/amlogic-camera.ko",
    "common_drivers/drivers/memory_ext/aml_smmu.ko",
    "common_drivers/drivers/memory_ext/user_fault.ko",
    "common_drivers/drivers/misc/khadas-mcu.ko",
    "common_drivers/drivers/net/ethernet/stmicro/stmmac/amlogic-phy-debug.ko",
    "common_drivers/drivers/net/ethernet/stmicro/stmmac/dwmac-dwc-qos-eth.ko",
    "common_drivers/drivers/net/ethernet/stmicro/stmmac/dwmac-meson.ko",
    "common_drivers/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.ko",
    "common_drivers/drivers/net/ethernet/stmicro/stmmac/stmmac-platform.ko",
    "common_drivers/drivers/net/ethernet/stmicro/stmmac/stmmac.ko",
    "common_drivers/drivers/net/mdio/amlogic-mdio-g12a.ko",
    "common_drivers/drivers/net/phy/amlogic-inphy.ko",
    "common_drivers/drivers/net/phy/amlogic-maxio.ko",
    "common_drivers/drivers/net/phy/amlogic-realtek.ko",
    "common_drivers/drivers/pci/controller/amlogic-pcie.ko",
    "common_drivers/drivers/rtc/amlogic-rtc.ko",
    "common_drivers/drivers/seckey/amlogic-seckey.ko",
    "common_drivers/drivers/soc_info/amlogic-socinfo.ko",
    "common_drivers/drivers/thermal/amlogic-thermal.ko",
    "common_drivers/drivers/usb/amlogic-usb.ko",
    "common_drivers/drivers/usb/dwc_otg.ko",
    "common_drivers/drivers/wireless/amlogic-wireless.ko",
    "common_drivers/sound/soc/amlogic/amlogic-snd-soc.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-ad82128.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-ad82584f.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-dummy.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-pa1.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-sy6026l.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-t9015.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-tas5707.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-tas5805.ko",
    "common_drivers/sound/soc/codecs/amlogic/amlogic-snd-codec-tl1.ko",
]

MODULES_OUT_REMOVE = [
    "fs/ntfs3/ntfs3.ko",
    "common_drivers/drivers/drm/aml_drm.ko",
    "common_drivers/drivers/media/camera/amlogic-camera.ko",
    "common_drivers/drivers/clk/meson/amlogic-clk-soc-s6.ko",
    "common_drivers/drivers/clk/meson/amlogic-clk-soc-s7.ko",
    "common_drivers/drivers/clk/meson/amlogic-clk-soc-s7d.ko",
    "common_drivers/drivers/gpio/amlogic-pinctrl-soc-s6.ko",
    "common_drivers/drivers/gpio/amlogic-pinctrl-soc-s7.ko",
    "common_drivers/drivers/gpio/amlogic-pinctrl-soc-s7d.ko",
]

GKI_MODULES_REMOVE = [
    "drivers/net/can/dev/can-dev.ko",
    "drivers/net/can/slcan.ko",
    "drivers/net/can/vcan.ko",
    "drivers/net/usb/aqc111.ko",
    "drivers/net/usb/cdc_eem.ko",
    "drivers/net/usb/rtl8150.ko",
    "drivers/usb/serial/ftdi_sio.ko",
    "drivers/usb/serial/usbserial.ko",
    "net/6lowpan/6lowpan.ko",
    "net/6lowpan/nhc_dest.ko",
    "net/6lowpan/nhc_fragment.ko",
    "net/6lowpan/nhc_hop.ko",
    "net/6lowpan/nhc_ipv6.ko",
    "net/6lowpan/nhc_mobility.ko",
    "net/6lowpan/nhc_routing.ko",
    "net/6lowpan/nhc_udp.ko",
    "net/8021q/8021q.ko",
    "net/can/can.ko",
    "net/can/can-bcm.ko",
    "net/can/can-gw.ko",
    "net/can/can-raw.ko",
    "net/ieee802154/6lowpan/ieee802154_6lowpan.ko",
    "net/nfc/nfc.ko",
    "net/rfkill/rfkill.ko",
]
